[package]
name = "onetagger-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.13"
alac = "0.5"
hound = "3.5"
rodio = "0.16"
lofty = "0.15"
redlux = "0.6"
pacmog = "0.4.1"
mp3-duration = "0.1"

onetagger-shared = { path = "../onetagger-shared" }

